[package]
name = "pallet-eth2-light-client"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.14", default-features = false }
serde = { version = "1.0.101", default-features = false, features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
webb-proposals = { git = "https://github.com/webb-tools/webb-rs.git", rev="a960eaf",default-features = false, features = ["scale", "evm", "substrate"] }
ethereum-types = { version = "0.14.1", default-features = false }
derive_more = { version = "^0.99.2", default-features = false }
rlp = { version = "0.5.0", default-features = false }
rlp-derive = { version = "0.1.0", default-features = false }
tiny-keccak = { version = "2.0", features = ["keccak"], default-features = false }
bitvec = { version = "1.0.0", default-features = false, features = ["atomic", "alloc"] }

eth-types = { path = "../../crates/eth-types", default-features = false, features = ["eth2"] }
eth2-ssz = { package = "webb-eth2-ssz", path = "../../crates/ssz", default-features = false }
merkle-proof = { package = "webb-merkle-proof", path = "../../crates/merkle-proof", default-features = false }
bls = { package = "webb-bls", path = "../../crates/bls", default-features = false }
tree-hash = { package = "webb-tree-hash", path = "../../crates/tree-hash", default-features = false }
tree-hash-derive = { package = "webb-tree-hash-derive", path = "../../crates/tree-hash-derive", default-features = false }
consensus = { package = "webb-consensus-types", path = "../../crates/consensus-types", default-features = false }

frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
hex = { version = "0.4.2", default-features = false, features = ["alloc"] }

[dev-dependencies]
anyhow = "1.0"
lazy_static = "1.4.0"
serde_json = { version = "1.0.58", default-features = false, features = ["alloc"] }
eth2-pallet-init = { package = "webb-eth2-pallet-init", path = "../../crates/eth2-pallet-init" }
async-trait = "0.1.72"

[features]
default = ["std"]
std = [
	"serde/std",
	"codec/std",
	"scale-info/std",
	"webb-proposals/std",
	"ethereum-types/std",
	"rlp/std",
	"bitvec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-core/std",
	"hex/std",

	# Local dependencies
	"bls/std",
	"consensus/std",
	"eth-types/std",
	"eth2-ssz/std",
	"tree-hash/std",
	"merkle-proof/std",
	
]

try-runtime = ["frame-support/try-runtime"]
