[package]
name = "eth2-pallet-init"
version = "0.1.0"
edition = "2021"

[dependencies]
tree_hash = { path = "../tree_hash", default-features = false }
merkle_proof = { path = "../merkle_proof", default-features = false }
consensus_types = { path = "../consensus_types" }
eth_rpc_client = { path = "../eth_rpc_client" }
eth-types = { path = "../eth-types/", default-features = false, features = ["eth2", "eip1559"]}
log = { version = "0.4", features = ["std", "serde"] }
clap = { version = "3.1.6", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0.74"
serde = { version = "1.0", default-features = false, features = ["derive"] }
toml = "0.5.9"
async-trait = "0.1.58"
sp-keyring = { default-features=false, version = "7.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.36" }

webb-relayer-utils = { git = "https://github.com/webb-tools/relayer.git" }
webb-relayer-types = { git = "https://github.com/webb-tools/relayer.git" }
webb = { git = "https://github.com/webb-tools/webb-rs.git", branch = "felix/relayer-anvil", default-features = false, features = [
    "evm-runtime",
    "substrate-runtime",
]}
subxt = "0.25.0"
scale = { package = "parity-scale-codec", version = "3", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
webb-proposals = { git = "https://github.com/webb-tools/webb-rs.git" }
tokio = { version = "1.1", default-features = false, features = ["macros", "rt", "time"] }
