enabled = true
name = "testnet config"
chain_id = 0
beacon_endpoint = "https://lodestar-goerli.chainsafe.io"
eth1_endpoint = "https://goerli.infura.io/v3/ETH1_INFURA_API_KEY"
substrate_endpoint = "ws://127.0.0.1:9944"
path_to_signer_secret_key = "/tmp/empty/secret_key"
ethereum_network = "Goerli"
substrate_network_name = "Tangle"
eth_requests_timeout_seconds = 30
validate_updates = true
verify_bls_signature = true
hashes_gc_threshold = 51000
beacon_rpc_version = "V1_5"
headers_batch_size = 33
interval_between_light_client_updates_submission_in_epochs = 1
max_blocks_for_finalization = 5000
state_requests_timeout_seconds = 1000
sleep_time_on_sync_secs = 0
sleep_time_after_submission_secs = 5
include_next_sync_committee_to_light_client = false
substrate_requests_timeout_seconds = 30