beacon_endpoint = "https://lodestar-goerli.chainsafe.io"
eth1_endpoint = "https://goerli.infura.io/v3/ETH1_INFURA_API_KEY"
path_to_current_sync_committee = "./eth2substrate-block-relay-rs/data/goerli_testdata/next_sync_committee_goerli_period_473.json"
path_to_next_sync_committee = "./eth2substrate-block-relay-rs/data/goerli_testdata/next_sync_committee_goerli_period_474.json"
path_to_execution_blocks_headers = "./eth2substrate-block-relay-rs/data/goerli_testdata/execution_block_headers_goerli_slots_3885697_3886176.json"
path_to_light_client_updates = "./eth2substrate-block-relay-rs/data/goerli_testdata/light_client_updates_goerli_slots_3885697_3886176.json"
path_to_attested_state = "./eth2substrate-block-relay-rs/data/goerli_testdata/beacon_state_goerli_slot_3885731.json"
path_to_finality_state = "./eth2substrate-block-relay-rs/data/goerli_testdata/beacon_state_goerli_slot_3885664.json"
network_name = "Goerli"
first_slot = 3885632
slot_without_block = 3885649
right_bound_in_slot_search = 3885800
left_empty_slot = 3885722
right_empty_slot = 3885723
slot_without_block_2 = 3885743
finalized_slot_before_new_period = 3891168
substrate_network_name="Tangle Test Network"
headers_batch_size = 33
substrate_endpoint = "ws://127.0.0.1:9944"
path_to_signer_secret_key = "/tmp/empty/secret_key"
ethereum_network = "Mainnet"
interval_between_light_client_updates_submission_in_epochs = 1
max_blocks_for_finalization = 5000
state_requests_timeout_seconds = 1000
sleep_time_on_sync_secs = 0
sleep_time_after_submission_secs = 5
include_next_sync_committee_to_light_client = false
substrate_requests_timeout_seconds = 30
eth_requests_timeout_seconds = 30
validate_updates = true
verify_bls_signature = true
hashes_gc_threshold = 51000
beacon_rpc_version = "V1_5"